export default [   
    {
        name: "Shane Griffith",
        state: "NJ",
        team: "Stanford Cardinal",
        yearsChampion: "2021 (165 lbs)",
        hometown: "Westwood, NJ",
        latitude: 40.9912,
        longitude: -74.0326,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/49991/griffith-shane/profile"
        },
        {
        name: "Austin O'Connor",
        state: "IL",
        team: "North Carolina Tar Heels",
        yearsChampion: "2021 (149 lbs)",
        hometown: "Lockport, IL",
        latitude: 41.5895,
        longitude: -88.0578,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/49214/oconnor-austin/profile"
        },
        {
        name: "AJ Ferrari",
        state: "TX",
        team: "Oklahoma State Cowboys",
        yearsChampion: "2021 (197 lbs)",
        hometown: "Allen, TX",
        latitude: 33.1032,
        longitude: -96.6707,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/62936/ferrari-aj/profile"
        },
        {
        name: "Aaron Brooks",
        state: "MD",
        team: "Penn State Nittany Lions",
        yearsChampion: "2021 (184 lbs)",
        hometown: "Hagerstown, MD",
        latitude: 39.6418,
        longitude: -77.72,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/54280/brooks-aaron/profile"
        },
        {
        name: "Zain Retherford",
        state: "PA",
        team: "Penn State Nittany Lions",
        yearsChampion: "2018 (149 lbs)",
        hometown: "Benton, PA",
        latitude: 41.1951,
        longitude: -76.3836,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/11781/retherford-zain/profile"
        },
        {
        name: "Michael Macchiavello",
        state: "NC",
        team: "North Carolina State Wolfpack",
        yearsChampion: "2018 (197 lbs)",
        hometown: "Monroe, NC",
        latitude: 34.9854,
        longitude: -80.5495,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/12532/macchiavello-michael/profile"
        },
        {
        name: "Roman Bravo-Young",
        state: "AZ",
        team: "Penn State Nittany Lions",
        yearsChampion: "2021 (133 lbs)",
        hometown: "Tucson, AZ",
        latitude: 32.2226,
        longitude: -110.9747,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/49665/bravo-young-roman/profile"
        },
        {
        name: "Jason Nolf",
        state: "PA",
        team: "Penn State Nittany Lions",
        yearsChampion: "2018 (157 lbs), 2019 (157 lbs)",
        hometown: "Yatesboro, PA",
        latitude: 40.8001,
        longitude: -79.3342,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/20303/nolf-jason/profile"
        },
        {
        name: "Kyle Snyder",
        state: "MD",
        team: "Ohio State Buckeyes",
        yearsChampion: "2018 (285 lbs)",
        hometown: "Woodbine, MD",
        latitude: 39.3738,
        longitude: -77.0569,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/20253/snyder-kyle/profile"
        },
        {
        name: "Anthony Ashnault",
        state: "NJ",
        team: "Rutgers Scarlet Knights",
        yearsChampion: "2019 (149 lbs)",
        hometown: "South Plainfield, NJ",
        latitude: 40.5793,
        longitude: -74.4115,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/11803/ashnault-anthony/profile"
        },
        {
        name: "Vincenzo Joseph",
        state: "PA",
        team: "Penn State Nittany Lions",
        yearsChampion: "2018 (165 lbs)",
        hometown: "Pittsburgh, PA",
        latitude: 40.4406,
        longitude: -79.9959,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/39542/joseph-vincenzo/profile"
        },
        {
        name: "Zahid Valencia",
        state: "CA",
        team: "Arizona State Sun Devils",
        yearsChampion: "2018 (174 lbs), 2019 (174 lbs)",
        hometown: "Bellflower, CA",
        latitude: 33.8817,
        longitude: -118.117,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/39501/valencia-zahid/profile"
        },
        {
        name: "Nick Suriano",
        state: "NJ",
        team: "Rutgers Scarlet Knights",
        yearsChampion: "2019 (133 lbs)",
        hometown: "Paramus, NJ",
        latitude: 40.9445,
        longitude: -74.0754,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/44648/suriano-nick/profile"
        },
        {
        name: "Yianni Diakomihalis",
        state: "NY",
        team: "Cornell Big Red",
        yearsChampion: "2018 (141 lbs), 2019 (141 lbs)",
        hometown: "Rochester, NY",
        latitude: 43.1566,
        longitude: -77.6088,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/49110/diakomihalis-yianni/profile"
        },
        {
        name: "Spencer Lee",
        state: "PA",
        team: "Iowa Hawkeyes",
        yearsChampion: "2018 (126 lbs), 2019 (126 lbs), 2021 (126 lbs)",
        hometown: "Murrysville, PA",
        latitude: 40.4284,
        longitude: -79.6975,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/49146/lee-spencer/profile"
        },
        {
        name: "Carter Starocci",
        state: "PA",
        team: "Penn State Nittany Lions",
        yearsChampion: "2021 (174 lbs)",
        hometown: "Erie, PA",
        latitude: 42.1292,
        longitude: -80.0851,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/58819/starocci-carter/profile"
        },
        {
        name: "Nick Lee",
        state: "IN",
        team: "Penn State Nittany Lions",
        yearsChampion: "2021 (141 lbs)",
        hometown: "Evansville, IN",
        latitude: 37.9716,
        longitude: -87.5711,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/49276/lee-nick/profile"
        },
        {
        name: "Gable Steveson",
        state: "MN",
        team: "Minnesota Golden Gophers",
        yearsChampion: "2021 (285 lbs)",
        hometown: "Apple Valley, MN",
        latitude: 44.7319,
        longitude: -93.2177,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/50624/steveson-gable/profile"
        },
        {
        name: "Drew Foster",
        state: "IA",
        team: "Northern Iowa Panthers",
        yearsChampion: "2019 (184 lbs)",
        hometown: "Burlington, IA",
        latitude: 40.8077,
        longitude: -91.1129,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/20212/foster-drew/profile"
        },
        {
        name: "David Carr",
        state: "OH",
        team: "Iowa State Cyclones",
        yearsChampion: "2021 (157 lbs)",
        hometown: "Canton, OH",
        latitude: 40.7989,
        longitude: -81.3784,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/51126/carr-david/profile"
        },
        {
        name: "Lewis Mehki",
        state: "NJ",
        team: "Virginia Tech Hokies",
        yearsChampion: "2019 (165 lbs)",
        hometown: "Bound Brook, NJ",
        latitude: 40.5684,
        longitude: -74.5385,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/49338/lewis-mekhi/profile"
        },
        {
        name: "Bo Nickal",
        state: "TX",
        team: "Penn State Nittany Lions",
        yearsChampion: "2018 (184 lbs), 2019 (197 lbs)",
        hometown: "Allen, TX",
        latitude: 33.1032,
        longitude: -96.6706,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/20302/nickal-bo/profile"
        },
        {
        name: "Anthony Cassar",
        state: "NJ",
        team: "Penn State Nittany Lions",
        yearsChampion: "2019 (285 lbs)",
        hometown: "Rocky Hill, NJ",
        latitude: 40.3998,
        longitude: -74.6343,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/20299/cassar-anthony/profile"
        },
        {
        name: "Seth Gross",
        state: "MN",
        team: "South Dakota State Jackrabbits",
        yearsChampion: "2018 (133 lbs)",
        hometown: "Apple Valley, MN",
        latitude: 44.7319,
        longitude: -93.2178,
        weight: null,
        wrestleStat: "https://www.wrestlestat.com/wrestler/19949/gross-seth/profile"
        }
];